### ISSUE TITLE
Support for multi tenant models

### ISSUE THREAD

**Issue by stalniy** [craftup/node-mongo-tenant#4]
In my application there are special kind of users which may have access to different tenants, that means tenantId should be an array.

Currently it's not supported, looks like the only needed change is inside `installMiddleware` method which intercepts mongoose queries

**Comment by tao** [comment]
I have this in my system but have dealt with it in a different way.

I have a `teams` model which has many `users`, A `team` can represent an (github) organisation, or a project, etc. and a `team` belongs to a single `mongo-tenant`, while the `users` model doesn't have a `mongo-tenant` plugin. 

So you can get the `users:teams[]` and `users:currentTeam` and retrieve mongoose models based on the current `team` the user is viewing. 

A `user` may belong to many `teams`, so you can fetch the `team` model and retrieve all the `users` that belong to the team; or you can select a `user` and retrieve all the `teams` they belong to.

This can become very difficult to deal with, and every system may have to handle with it in very specific ways, especially when you start to consider different access rights according to `tenants`, or billing and subscriptions based on `teams`.

Perhaps you should consider thinking about another way of handling this instead of changing this `mongo-tenant` package to suit your requirements? As everyone else who uses this package may have different needs and it might be better to keep it as simple as possible, or create a clone and modify it for what you need.

And how will it impact performance if you have to search through arrays of multiple tenants for each query?

Just a suggestion... I'm not against any changes, I'm just saying it can become complicated very quickly and it might be better to deal with that logic on another level.

**Comment by stalniy** [comment]
@tao make sense, thanks for hints!
