### ISSUE TITLE
Schema.countDocuments returns total count of elements ignoring tenantId

### ISSUE THREAD

**Issue by RsknCankov** [craftup/node-mongo-tenant#45]
Hello,
has anyone face issue when calling "countdocuments()" function on the schema which has tenant plugin included it returns all the records ignoring their tenatIds?

**Comment by gosuhiman** [comment]
@RsknCankov this plugin does not implement multi-tenancy to all methods of a mongoose model, e.g. `countDocuments` and `deleteMany` are ignored. You can look in the source to check which methods are implemented.

To solve your problem - `count` method is implemented, so you can use it instead of `countDocuments`.

**Comment by RsknCankov** [comment]
@gosuhiman I am using it on an abstract layer where I do not know what type of mongoose schema I am using (Tenant or NonTenant one) and I used courtDocuments, because mongoose has deprecated count. I implemented a solution by using hasTenantContext getter and now everything works just fine. Thanks!

**Comment by alrik** [comment]
@RsknCankov Thanks for your report and thanks @gosuhiman for instant support :+1: 

I created a ticket to complete mongoose API support in mongo-tenant. 
Any help on gathering the missing methods is very welcome :)
see #46
