### ISSUE TITLE
Collection-level multi-tenancy

### ISSUE THREAD

**Issue by HaiderAliAslam** [craftup/node-mongo-tenant#50]
I am a bit curious on why collection-level multi-tenancy is not recommended. I am particularly interested in micro-services scenario where each 'function' of the business is a separate microservice having a separate database. So, each database is not going to have a very large number of collections if collection-level multi-tenancy is applied. Would like to hear from you on this. Thanks

**Comment by baranga** [comment]
@HaiderAliAslam that's a good question!

Back in the days when we started developing this plugin there was a limit on the maximum number of collections per database. So having n collections per tenant could lead to hitting the limit with enough tenants. Since MongoDB 3.0 the WiredTiger storage engine is available which doesn't has that limit anymore ([more here](https://docs.mongodb.com/manual/reference/limits/#Number-of-Namespaces)).

That aside the administration of collections may be complicated. Configuration of indexes, sharding options, validation schemas may need to be done for all "similar" collections over all tenants.

So for me it doesn't add any value from security or administration perspective but just complicates things. Therefore I wouldn't consider that option.

Nevertheless we plan to support that option in version 2.

**Comment by HaiderAliAslam** [comment]
Thanks for your comments @baranga!
